properties = [
  {
    '_id': "1",
    'rating': 3.5,
    'ratingCount': 34,
    'description':
      "Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units. Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.",
    'address': "Block F, Johar Town",
    'city': "Lahore",
    'state': "Punjab",
    'baths': 4,
    'beds': 5,
    'area': "5",
    'image': "/images/hero-home1.jpg",
    'rent': 50000,
  },
  {
    '_id': "2",
    'rating': 5,
    'ratingCount': 34,
    'description':
      "Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units. Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.",
    'address': "Block D, Model Town",
    'city': "Lahore",
    'state': "Punjab",
    'baths': 3,
    'beds': 5,
    'area': "3",
    'image': "/images/hero-home1.jpg",
    'rent': 520000,
  },
  {
    '_id': "3",
    'rating': 4.5,
    'ratingCount': 55,
    'description':
      "Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units. Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.",
    'address': "Block N, Nishtar Town",
    'city': "Lahore",
    'state': "Punjab",
    'baths': 2,
    'beds': 6,
    'area': "10",
    'image': "/images/hero-home4.png",
    'rent': 10000,
  },
  {
    '_id': "4",
    'rating': 2,
    'ratingCount': 2,
    'description':
      "Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units. Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.",
    'address': "Block F, Bilal Town",
    'city': "Lahore",
    'state': "Punjab",
    'baths': 6,
    'beds': 8,
    'area': "11",
    'image': "/images/hero-home4.png",
    'rent': 70000,
  },

  {
    '_id': "4",
    'rating': 5,
    'ratingCount': 4,
    'description':
      "Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units. Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.",
    'address': "Block F, Bilal Town",
    'city': "Lahore",
    'state': "Punjab",
    'baths': 6,
    'beds': 8,
    'area': "11",
    'image': "/images/hero-home4.png",
    'rent': 70000,
  },
  {
    '_id': "5",
    'rating': 5,
    'ratingCount': 334,
    'description':
      "Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units. Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.",
    'address': "Block F, Bilal Town",
    'city': "Lahore",
    'state': "Punjab",
    'baths': 6,
    'beds': 8,
    'area': "11",
    'image': "/images/hero-home4.png",
    'rent': 70000,
  },
  {
    '_id': "6",
    'rating': 4,
    'ratingCount': 122,
    'description':
      "Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units. Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.",
    'address': "Block F, Bilal Town",
    'city': "Lahore",
    'state': "Punjab",
    'baths': 6,
    'beds': 8,
    'area': "11",
    'image': "/images/hero-home4.png",
    'rent': 70000,
  },
  {
    '_id': "7",
    'rating': 5,
    'ratingCount': 34,
    'description':
      "Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units. Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.",
    'address': "Block F, Bilal Town",
    'city': "Lahore",
    'state': "Punjab",
    'baths': 6,
    'beds': 8,
    'area': "11",
    'image': "/images/hero-home4.png",
    'rent': 70000,
  },
  {
    '_id': "8",
    'rating': 5,
    'ratingCount': 34,
    'description':
      "Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units. Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.Look no further as we have listed the best Bungalow just for you! This could be your chance to buy such a precious real e'state' asset. Don't miss out on these 7  Marla units.",
    'address': "Block F, Bilal Town",
    'city': "Lahore",
    'state': "Punjab",
    'baths': 6,
    'beds': 8,
    'area': "11",
    'image': "/images/hero-home4.png",
    'rent': 70000,
  },
];

