# Generated by Django 3.2.10 on 2021-12-27 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('listed_properties', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='base.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('total_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('no_of_baths', models.IntegerField(default=0)),
                ('no_of_beds', models.IntegerField(default=0)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyAddress', to='base.address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlordProperty', to='base.landlord')),
            ],
        ),
        migrations.AddField(
            model_name='landlord',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlordUserProfile', to='base.userprofile'),
        ),
    ]
