# Generated by Django 3.2.10 on 2021-12-27 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_property_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenantUserProfile', to='base.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(null=True)),
                ('given_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenantReview', to='base.tenant')),
                ('given_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlordReview', to='base.landlord')),
                ('on_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propertyReview', to='base.property')),
            ],
        ),
    ]
