# Generated by Django 3.2.10 on 2022-03-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
