# Generated by Django 3.2.10 on 2022-03-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20220314_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_message', to='base.userprofile')),
                ('sent_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_to_userprofile', to='base.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='', max_length=255, null=True)),
                ('chat_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_with_userprofile', to='base.userprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_userprofile', to='base.userprofile')),
                ('for_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_property', to='base.property')),
            ],
        ),
    ]
