# Generated by Django 3.2.10 on 2022-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='House', max_length=200),
        ),
    ]
