# Generated by Django 3.2.10 on 2022-02-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(default='Active', max_length=255),
        ),
    ]
